# Generated by Django 5.2.4 on 2025-07-29 18:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('asset_type', models.CharField(blank=True, choices=[('MUTUAL_FUNDS', 'Mutual Funds'), ('TREASURY_BILLS', 'Treasury Bills'), ('NAIRA_BONDS', 'Naira Bonds')], max_length=50, null=True)),
                ('asset_type_description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=50, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('indicative_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prospectus_url', models.URLField(blank=True, null=True)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_holding_days', models.PositiveIntegerField(blank=True, help_text='Minimum holding period in days', null=True)),
                ('min_subsequent_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('thirty_day_yield_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('one_year_yield_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_to_date_yield_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('five_year_yield_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('historical_data', models.JSONField(blank=True, help_text='Historical data for the investment product', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
